name: 1-actions-ci-cd-acr-aks

on:
  push:
    branches: 
      - main
    paths: .github/workflows/1-actions-ci-cd-acr-aks.yml
  pull_request:
    branches: 
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build-deploy-aks:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: dotnetmicro # name of Docker Hub ID
      IMAGE_NAME: dotnetwebapp
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
      
      CLUSTER_NAME: eshop-learn-aks
      RESOURSE_GROUP: eshop-learn-rg

    steps:

      - name: Git Checkout
        uses: actions/checkout@v2
        
      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}
          image:  azure-vote-front
          folder: azure-vote
          branch: master
          tag: latest
