name: 1-actions-ci-cd-acr-aks

on:
  push:
    branches: 
      - main
    paths: .github/workflows/1-actions-ci-cd-acr-aks.yml
  pull_request:
    branches: 
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build-deploy-aks:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: dotnetmicro # name of Docker Hub ID
      IMAGE_NAME: dotnetwebapp
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
      
      CLUSTER_NAME: eshop-learn-aks
      RESOURSE_GROUP: eshop-learn-rg

    steps:

      - name: Git Checkout
        uses: actions/checkout@v2
        
      - name: Docker build, Clair scan, ACR push
         # You may pin to the exact commit or the version.
         # uses: MaciejBoguta/docker-clair-acr-action@ad36c9f1f42c147161ff129352a9f04706d07483
        uses: MaciejBoguta/docker-clair-acr-action@v0.2.0
        with:
          # Container repository and image name
          image-name: dotnetmicro/dotnetwebapp
          # Image tag, defaults to latest
          tag: ${{ github.run_number }} # optional, default is latest
          # Should image be pushed to ACR
          should-push-to-acr: "true"
          # Azure client id for authentication to ACR
          client-id: "88c90c90-6ecc-47b5-8b79-973288dbe40b"
          # Azure client secret for authentication to ACR
          client-secret: "82n8Q~txQpNc0NdZ6QqbImoPOGT23M1eMzl5la_n"
          # ACR instance name
          acr-name: ramucontainerregistry.azurecr.io
